## Вариант 7

В работе рассматриваются:

1. матрицы Гильберта $H_n$ и их числа обусловленности;
2. решение системы линейных уравнений методом `np.linalg.solve`;
3. решение этой же системы методом Зейделя;
4. решение методом верхней релаксации при разных значениях параметра $\omega$.

In [11]:

import numpy as np
import pandas as pd
from IPython.display import display

pd.set_option("display.precision", 2)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 30)


# Задание 1

Матрицей Гильберта называется матрица

$$
H_n = \left(\frac{1}{i+j-1}\right), \quad i,j=1,2,\ldots,n.
$$

Для $n = 2,4,6,\ldots,14$ нужно:

- сформировать матрицу Гильберта $H_n$;
- найти число обусловленности $\operatorname{cond}(H_n)$ с помощью `np.linalg.cond`;
- вычислить вектор $f = H_nx$, где $x=(1,1,\ldots,1)^T$;
- решить систему $H_nz=f$ с помощью `np.linalg.solve`;
- вывести покомпонентную разность $z-x$.

In [12]:

def hilbert_matrix(n):
    # Создает матрицу Гильберта размера n x n.
    H = np.zeros((n, n), dtype=float)
    for i in range(n):
        for j in range(n):
            H[i, j] = 1 / (i + j + 1)
    return H

summary_rows = []
diff_rows = []

for n in range(2, 15, 2):
    H = hilbert_matrix(n)
    x = np.ones(n)
    f = H @ x
    z = np.linalg.solve(H, f)
    diff = z - x
    
    summary_rows.append({
        "n": n,
        "cond(H_n)": np.linalg.cond(H),
        "max |z - x|": np.max(np.abs(diff))
    })
    
    row = {"n": n}
    for i, value in enumerate(diff, start=1):
        row[f"z{i}-x{i}"] = value
    diff_rows.append(row)

summary_df = pd.DataFrame(summary_rows)
diff_df = pd.DataFrame(diff_rows)

print("Числа обусловленности и максимальная ошибка:")
display(summary_df)

print("Покомпонентная разность z - x:")
display(diff_df)

Числа обусловленности и максимальная ошибка:

    n  cond(H_n)  max |z - x|
0   2   1.93e+01     6.66e-16
1   4   1.55e+04     7.05e-13
2   6   1.50e+07     2.39e-10
3   8   1.53e+10     4.08e-07
4  10   1.60e+13     7.46e-04
5  12   1.73e+16     1.66e+00
6  14   3.75e+17     2.28e+01

Покомпонентная разность z - x:

,n,z1-x1,z2-x2,z3-x3,z4-x4,z5-x5,z6-x6,z7-x7,z8-x8,z9-x9,z10-x10,z11-x11,z12-x12,z13-x13,z14-x14
0,2,4.44e-16,-6.66e-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,-2.68e-14,2.95e-13,-7.05e-13,4.57e-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6,-4.70e-13,1.30e-11,-8.58e-11,2.19e-10,-2.39e-10,9.34e-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8,-2.67e-11,1.45e-09,-1.92e-08,1.05e-07,-2.86e-07,4.08e-07,-2.92e-07,8.30e-08,NaN,NaN,NaN,NaN,NaN,NaN
4,10,-2.09e-09,1.80e-07,-3.83e-06,3.48e-05,-1.66e-04,4.55e-04,-7.46e-04,7.20e-04,-3.78e-04,8.30e-05,NaN,NaN,NaN,NaN
5,12,-1.54e-07,1.97e-05,-6.25e-04,8.56e-03,-6.31e-02,2.78e-01,-7.78e-01,1.41e+00,-1.66e+00,1.22e+00,-0.51,0.09,NaN,NaN
6,14,-2.83e-07,3.84e-05,-1.26e-03,1.71e-02,-1.17e-01,3.98e-01,-3.98e-01,-2.02e+00,9.37e+00,-1.91e+01,22.84,-16.35,6.54,-1.12

Чем больше $n$, тем больше число обусловленности $\operatorname{cond}(H_n)$.

Если матрица хорошо обусловлена, то разность $z-x$ должна быть близка к нулю. Для матриц Гильберта при больших $n$ число обусловленности становится очень большим, поэтому даже при решении системы с известным точным ответом появляются заметные вычислительные ошибки.


# Задание 2

Для варианта 7 дана система:

$$
\begin{cases}
8x+y+z=10,\\
x+6y+z=8,\\
x+y+7z=9.
\end{cases}
$$

В матричном виде:

$$
Ax=f,
$$

где

$$
A =
\begin{pmatrix}
8 & 1 & 1 \\
1 & 6 & 1 \\
1 & 1 & 7
\end{pmatrix},
\quad
f =
\begin{pmatrix}
10 \\
8 \\
9
\end{pmatrix}.
$$

In [13]:

A = np.array([
    [8, 1, 1],
    [1, 6, 1],
    [1, 1, 7]
], dtype=float)

f = np.array([10, 8, 9], dtype=float)

print("Матрица A:")
display(pd.DataFrame(A, columns=["x", "y", "z"]))

print("Вектор f:")
display(pd.DataFrame(f, columns=["f"]))

Матрица A:

     x    y    z
0  8.0  1.0  1.0
1  1.0  6.0  1.0
2  1.0  1.0  7.0

Вектор f:

      f
0  10.0
1   8.0
2   9.0


## Решение системы напрямую

Сначала решим систему стандартной функцией:

$$
x = A^{-1}f.
$$

В коде используем `np.linalg.solve(A, f)`.

In [14]:

x_direct = np.linalg.solve(A, f)
residual_direct = f - A @ x_direct

print("Решение, полученное np.linalg.solve:")
direct_df = pd.DataFrame({
    "переменная": ["x", "y", "z"],
    "значение": x_direct
})
display(direct_df)

print("Невязка r = f - A x:")
residual_direct_df = pd.DataFrame({
    "компонента": ["r1", "r2", "r3"],
    "значение": residual_direct
})
display(residual_direct_df)

Решение, полученное np.linalg.solve:

  переменная  значение
0          x       1.0
1          y       1.0
2          z       1.0

Невязка r = f - A x:

  компонента  значение
0         r1       0.0
1         r2       0.0
2         r3       0.0


## Метод Зейделя

Метод Зейделя строит последовательность приближений $x^{(k)}$.

Для каждой компоненты используется формула:

$$
x_i^{(k+1)} = \frac{1}{a_{ii}}\left(f_i - \sum_{j<i}a_{ij}x_j^{(k+1)} - \sum_{j>i}a_{ij}x_j^{(k)}\right).
$$

В качестве начального приближения возьмем

$$
x^{(0)}=(0,0,0)^T.
$$

Невязку будем считать по формуле:

$$
r^{(k)} = f - Ax^{(k)}.
$$

Для контроля сходимости будем использовать норму:

$$
\|r^{(k)}\|_{\infty}=\max_i |r_i^{(k)}|.
$$

In [15]:

def gauss_seidel(A, f, x0=None, eps=1e-10, max_iter=100):
    # Метод Зейделя для системы A x = f.
    A = np.array(A, dtype=float)
    f = np.array(f, dtype=float)
    n = len(f)
    
    if x0 is None:
        x = np.zeros(n)
    else:
        x = np.array(x0, dtype=float).copy()
    
    history = []
    
    for k in range(1, max_iter + 1):
        x_old = x.copy()
        
        for i in range(n):
            left_sum = np.dot(A[i, :i], x[:i])
            right_sum = np.dot(A[i, i+1:], x_old[i+1:])
            x[i] = (f[i] - left_sum - right_sum) / A[i, i]
        
        residual = f - A @ x
        residual_inf = np.linalg.norm(residual, ord=np.inf)
        residual_2 = np.linalg.norm(residual, ord=2)
        
        history.append({
            "iteration": k,
            "x": x[0],
            "y": x[1],
            "z": x[2],
            "||r||_inf": residual_inf,
            "||r||_2": residual_2
        })
        
        if residual_inf < eps:
            break
    
    return x, pd.DataFrame(history)

x_seidel, seidel_history = gauss_seidel(A, f, eps=1e-10)

print("Решение методом Зейделя:")
display(pd.DataFrame({
    "переменная": ["x", "y", "z"],
    "значение": x_seidel
}))

print("Невязки на каждой итерации метода Зейделя:")
display(seidel_history)

print(f"Количество итераций: {len(seidel_history)}")

Решение методом Зейделя:

  переменная  значение
0          x       1.0
1          y       1.0
2          z       1.0

Невязки на каждой итерации метода Зейделя:

   iteration     x     y     z  ||r||_inf   ||r||_2
0          1  1.25  1.12  0.95   2.07e+00  2.28e+00
1          2  0.99  1.01  1.00   6.12e-02  8.12e-02
2          3  1.00  1.00  1.00   9.81e-03  9.82e-03
3          4  1.00  1.00  1.00   4.02e-04  4.25e-04
4          5  1.00  1.00  1.00   9.25e-06  1.07e-05
5          6  1.00  1.00  1.00   1.51e-06  1.52e-06
6          7  1.00  1.00  1.00   7.42e-08  7.66e-08
7          8  1.00  1.00  1.00   1.56e-09  1.56e-09
8          9  1.00  1.00  1.00   2.25e-10  2.28e-10
9         10  1.00  1.00  1.00   1.32e-11  1.34e-11

Количество итераций: 10


## Метод верхней релаксации

Метод верхней релаксации отличается от метода Зейделя тем, что новое значение берется с весом $\omega$:

$$
x_i^{(k+1)} = (1-\omega)x_i^{(k)} + \frac{\omega}{a_{ii}}\left(f_i - \sum_{j<i}a_{ij}x_j^{(k+1)} - \sum_{j>i}a_{ij}x_j^{(k)}\right).
$$

При $\omega=1$ метод верхней релаксации совпадает с методом Зейделя.

Проверим несколько значений $\omega$ из диапазона $[1;2]$ и выберем то, при котором сходимость самая быстрая.

In [16]:

def sor(A, f, omega, x0=None, eps=1e-10, max_iter=500):
    # Метод верхней релаксации для системы A x = f.
    A = np.array(A, dtype=float)
    f = np.array(f, dtype=float)
    n = len(f)
    
    if x0 is None:
        x = np.zeros(n)
    else:
        x = np.array(x0, dtype=float).copy()
    
    history = []
    
    for k in range(1, max_iter + 1):
        x_old = x.copy()
        
        for i in range(n):
            left_sum = np.dot(A[i, :i], x[:i])
            right_sum = np.dot(A[i, i+1:], x_old[i+1:])
            x_gs = (f[i] - left_sum - right_sum) / A[i, i]
            x[i] = (1 - omega) * x_old[i] + omega * x_gs
        
        residual = f - A @ x
        residual_inf = np.linalg.norm(residual, ord=np.inf)
        residual_2 = np.linalg.norm(residual, ord=2)
        
        history.append({
            "omega": omega,
            "iteration": k,
            "x": x[0],
            "y": x[1],
            "z": x[2],
            "||r||_inf": residual_inf,
            "||r||_2": residual_2
        })
        
        if residual_inf < eps:
            break
    
    return x, pd.DataFrame(history)


## Подбор оптимального значения $\omega$

Переберем значения $\omega$ от $1$ до $2$ с шагом $0.01$.

Оптимальным будем считать то значение $\omega$, при котором метод достиг точности быстрее всего, то есть за минимальное количество итераций.

In [17]:

omega_grid = np.round(np.arange(1.00, 2.01, 0.01), 2)
summary_sor = []

for omega in omega_grid:
    x_sor, history_sor = sor(A, f, omega, eps=1e-10, max_iter=500)
    final_residual = history_sor["||r||_inf"].iloc[-1]
    converged = final_residual < 1e-10
    
    summary_sor.append({
        "omega": omega,
        "iterations": len(history_sor),
        "final ||r||_inf": final_residual,
        "converged": converged,
        "x": x_sor[0],
        "y": x_sor[1],
        "z": x_sor[2]
    })

summary_sor_df = pd.DataFrame(summary_sor)
converged_sor_df = summary_sor_df[summary_sor_df["converged"]].copy()
best_sor = converged_sor_df.sort_values(["iterations", "omega"]).iloc[0]

print("Первые 15 лучших значений omega по числу итераций:")
display(converged_sor_df.sort_values(["iterations", "omega"]).head(15))

print("Лучшее найденное значение omega:")
display(pd.DataFrame([best_sor]))

Первые 15 лучших значений omega по числу итераций:

    omega  iterations  final ||r||_inf  converged    x    y    z
1    1.01           9         6.16e-11       True  1.0  1.0  1.0
0    1.00          10         1.32e-11       True  1.0  1.0  1.0
2    1.02          10         8.12e-12       True  1.0  1.0  1.0
3    1.03          10         3.14e-11       True  1.0  1.0  1.0
4    1.04          10         7.05e-11       True  1.0  1.0  1.0
5    1.05          11         1.29e-11       True  1.0  1.0  1.0
6    1.06          11         9.28e-11       True  1.0  1.0  1.0
7    1.07          12         2.24e-11       True  1.0  1.0  1.0
8    1.08          12         7.73e-11       True  1.0  1.0  1.0
9    1.09          13         2.26e-11       True  1.0  1.0  1.0
10   1.10          13         6.42e-11       True  1.0  1.0  1.0
11   1.11          14         2.11e-11       True  1.0  1.0  1.0
12   1.12          14         5.58e-11       True  1.0  1.0  1.0
13   1.13          15         1.94e-11       True  1.0  1.0  1.0
14   1.14          15         5.01e-11       True  1.0  1.0  1.0

Лучшее найденное значение omega:

   omega  iterations  final ||r||_inf  converged    x    y    z
1   1.01           9         6.16e-11       True  1.0  1.0  1.0


## Невязки метода верхней релаксации для нескольких $\omega$

Выведем невязки на каждой итерации для нескольких значений:

$$
\omega \in \{1.00, 1.01, 1.10, 1.20, 1.50\}.
$$

Значение $\omega=1.00$ оставлено для сравнения, потому что при $\omega=1$ метод верхней релаксации совпадает с методом Зейделя.

In [18]:

omegas_to_show = [1.00, 1.01, 1.10, 1.20, 1.50]
all_histories = []

for omega in omegas_to_show:
    x_sor, history_sor = sor(A, f, omega, eps=1e-10, max_iter=500)
    all_histories.append(history_sor)

sor_histories_df = pd.concat(all_histories, ignore_index=True)

print("Невязки на каждой итерации для выбранных omega:")
display(sor_histories_df)

Невязки на каждой итерации для выбранных omega:

    omega  iteration     x     y     z  ||r||_inf   ||r||_2
0    1.00          1  1.25  1.12  0.95   2.07e+00  2.28e+00
1    1.00          2  0.99  1.01  1.00   6.12e-02  8.12e-02
2    1.00          3  1.00  1.00  1.00   9.81e-03  9.82e-03
3    1.00          4  1.00  1.00  1.00   4.02e-04  4.25e-04
4    1.00          5  1.00  1.00  1.00   9.25e-06  1.07e-05
5    1.00          6  1.00  1.00  1.00   1.51e-06  1.52e-06
6    1.00          7  1.00  1.00  1.00   7.42e-08  7.66e-08
7    1.00          8  1.00  1.00  1.00   1.56e-09  1.56e-09
8    1.00          9  1.00  1.00  1.00   2.25e-10  2.28e-10
9    1.00         10  1.00  1.00  1.00   1.32e-11  1.34e-11
10   1.01          1  1.26  1.13  0.95   2.19e+00  2.41e+00
11   1.01          2  0.99  1.01  1.00   9.87e-02  1.07e-01
12   1.01          3  1.00  1.00  1.00   8.99e-03  9.12e-03
13   1.01          4  1.00  1.00  1.00   1.59e-04  1.60e-04
14   1.01          5  1.00  1.00  1.00   2.44e-05  2.44e-05
15   1.01          6  1.00  1.00  1.00   7.80e-07  8.83e-07
16   1.01          7  1.00  1.00  1.00   4.25e-08  4.51e-08
17   1.01          8  1.00  1.00  1.00   3.46e-09  3.52e-09
18   1.01          9  1.00  1.00  1.00   6.16e-11  6.25e-11
19   1.10          1  1.38  1.21  1.01   3.22e+00  3.69e+00
20   1.10          2  0.93  0.99  1.01   5.43e-01  5.56e-01
21   1.10          3  1.01  1.00  1.00   4.89e-02  5.05e-02
22   1.10          4  1.00  1.00  1.00   3.52e-03  3.73e-03
23   1.10          5  1.00  1.00  1.00   7.35e-04  8.62e-04
24   1.10          6  1.00  1.00  1.00   1.20e-04  1.22e-04
25   1.10          7  1.00  1.00  1.00   8.04e-06  9.45e-06
26   1.10          8  1.00  1.00  1.00   9.76e-07  1.19e-06
27   1.10          9  1.00  1.00  1.00   2.31e-07  2.50e-07
28   1.10         10  1.00  1.00  1.00   2.86e-08  2.89e-08
29   1.10         11  1.00  1.00  1.00   1.50e-09  1.97e-09
30   1.10         12  1.00  1.00  1.00   2.86e-10  3.85e-10
31   1.10         13  1.00  1.00  1.00   6.42e-11  6.66e-11
32   1.20          1  1.50  1.30  1.06   4.36e+00  5.11e+00
33   1.20          2  0.85  0.96  1.02   1.26e+00  1.31e+00
34   1.20          3  1.03  1.00  0.99   2.60e-01  2.62e-01
35   1.20          4  1.00  1.00  1.00   3.41e-02  4.08e-02
36   1.20          5  1.00  1.00  1.00   7.03e-03  7.59e-03
37   1.20          6  1.00  1.00  1.00   1.69e-03  2.37e-03
38   1.20          7  1.00  1.00  1.00   5.73e-04  6.21e-04
39   1.20          8  1.00  1.00  1.00   1.16e-04  1.21e-04
40   1.20          9  1.00  1.00  1.00   1.19e-05  1.89e-05
41   1.20         10  1.00  1.00  1.00   4.10e-06  4.76e-06
42   1.20         11  1.00  1.00  1.00   1.23e-06  1.52e-06
43   1.20         12  1.00  1.00  1.00   3.55e-07  3.73e-07
44   1.20         13  1.00  1.00  1.00   6.48e-08  6.82e-08
45   1.20         14  1.00  1.00  1.00   7.78e-09  1.08e-08
46   1.20         15  1.00  1.00  1.00   2.47e-09  2.99e-09
47   1.20         16  1.00  1.00  1.00   7.76e-10  9.18e-10
48   1.20         17  1.00  1.00  1.00   2.04e-10  2.12e-10
49   1.20         18  1.00  1.00  1.00   3.37e-11  3.67e-11
50   1.50          1  1.88  1.53  1.20   7.73e+00  9.26e+00
51   1.50          2  0.43  0.83  1.06   4.71e+00  4.96e+00
52   1.50          3  1.31  0.99  0.91   2.36e+00  2.40e+00
53   1.50          4  0.86  1.06  1.06   9.56e-01  1.07e+00
54   1.50          5  1.04  0.94  0.97   3.28e-01  4.75e-01
55   1.50          6  0.99  1.04  1.01   2.26e-01  2.41e-01
56   1.50          7  0.99  0.98  1.00   1.19e-01  1.35e-01
57   1.50          8  1.01  1.01  1.00   5.27e-02  7.28e-02
58   1.50          9  1.00  1.00  1.00   2.93e-02  3.56e-02
59   1.50         10  1.00  1.00  1.00   1.15e-02  1.64e-02
60   1.50         11  1.00  1.00  1.00   6.41e-03  8.12e-03
61   1.50         12  1.00  1.00  1.00   3.64e-03  4.79e-03
62   1.50         13  1.00  1.00  1.00   2.06e-03  2.92e-03
63   1.50         14  1.00  1.00  1.00   1.38e-03  1.63e-03
64   1.50         15  1.00  1.00  1.00   7.63e-04  8.17e-04
65   1.50         16  1.00  1.00  1.00   3.26e-04  3.72e-04
66   1.50         17  1.00  1.00  1.00   1.06e-04  1.70e-04
67   1.50         18  1.00  1.00  1.00   7.63e-05  9.02e-05
68   1.50         19  1.00  1.00  1.00   4.41e-05  5.32e-05
69   1.50         20  1.00  1.00  1.00   2.28e-05  3.00e-05
70   1.50         21  1.00  1.00  1.00   1.34e-05  1.52e-05
71   1.50         22  1.00  1.00  1.00   5.95e-06  7.03e-06
72   1.50         23  1.00  1.00  1.00   2.30e-06  3.25e-06
73   1.50         24  1.00  1.00  1.00   1.38e-06  1.75e-06
74   1.50         25  1.00  1.00  1.00   8.41e-07  1.06e-06
75   1.50         26  1.00  1.00  1.00   4.66e-07  6.08e-07
76   1.50         27  1.00  1.00  1.00   2.82e-07  3.14e-07
77   1.50         28  1.00  1.00  1.00   1.31e-07  1.47e-07
78   1.50         29  1.00  1.00  1.00   4.31e-08  6.63e-08
79   1.50         30  1.00  1.00  1.00   2.66e-08  3.41e-08
80   1.50         31  1.00  1.00  1.00   1.68e-08  2.02e-08
81   1.50         32  1.00  1.00  1.00   8.41e-09  1.17e-08
82   1.50         33  1.00  1.00  1.00   5.38e-09  6.16e-09
83   1.50         34  1.00  1.00  1.00   2.60e-09  2.91e-09
84   1.50         35  1.00  1.00  1.00   8.97e-10  1.31e-09
85   1.50         36  1.00  1.00  1.00   4.89e-10  6.65e-10
86   1.50         37  1.00  1.00  1.00   3.26e-10  3.92e-10
87   1.50         38  1.00  1.00  1.00   1.63e-10  2.31e-10
88   1.50         39  1.00  1.00  1.00   1.07e-10  1.23e-10
89   1.50         40  1.00  1.00  1.00   5.35e-11  5.90e-11

1. Для варианта 7 точное решение системы:

$$
x=1, \quad y=1, \quad z=1.
$$

2. Метод Зейделя сходится к этому решению за несколько итераций.

3. Метод верхней релаксации при $\omega=1$ совпадает с методом Зейделя.

4. По перебору значений $\omega$ с шагом $0.01$ оптимальное значение получилось около:

$$
\omega \approx 1.01.
$$

5. При больших значениях $\omega$ сходимость становится медленнее, поэтому для данной системы слишком сильная верхняя релаксация не нужна.